### ISSUE TITLE
Yarn error on resource start (ZAP-Hosting)

### ISSUE THREAD

**Issue by Nightwalkersfear** [sadboilogan/discordroles#1]
Error on startup. Gameserver version 29.6.7.

I am not familiair with node.js so this seems out of my league. I've been browsing around and I've figured this same issue appears for resources like: live_map and TokoVOIP. 

Is this issue related to this resource, or is it something else?

```
Running build tasks on resource discordroles - it'll restart once completed.
Couldn't start resource discordroles.
yarn install v1.22.5
warning package.json: No license field
info No lockfile found.
warning No license field
[2/4] Fetching packages...
[3/4] Linking dependencies...
error Could not write file "C:\\cygwin\\home\\zapXXXXX\\gXXXXX\\gta5-fivem\\server-data\\resources\\[Discord Synchronizations]\\discordroles\\yarn-error.log": "EPERM: operation not permitted, open 'C:\\cygwin\\home\\zapXXXXXX\\gXXXXXX\\gta5-fivem\\server-data\\resources\\[Discord Synchronizations]\\discordroles\\yarn-error.log'"
error An unexpected error occurred: "EPERM: operation not permitted, mkdir 'C:\\cygwin\\home\\zapXXXXX\\gXXXXXX\\gta5-fivem\\server-data\\resources\\[Discord Synchronizations]\\discordroles\\node_modules'".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Running build tasks on resource discordroles - it'll restart once completed.
Couldn't start resource discordroles.
```

**Comment by logan-mcgee** [comment]
i guess zap has wrong permissions. nothing i can fix on my end, youd probably have to contact them about such issues maybe.

**Comment by Nightwalkersfear** [comment]
So I have managed to find a workaround which I'd like to share for other zap-users with issues. 

Locally download and set up the discordroles file and configs. Then inside your folder run node js to afterwards 'npm install' the package.json. (how to: [here](https://www.youtube.com/watch?v=q19PLYrv9r4&ab_channel=Codevolution)). Then after you've done that delete package.json and package-lock file and move the files over to your server resources folder and start/ensure it inside the server.cfg. 

That made this work for me.

**Comment by logan-mcgee** [comment]
annoying that such a hack is needed when in reality all zap needs to do is fix permissions with yarn or so. thanks for actually mentioning how you fixed it tho :)

**Comment by Nightwalkersfear** [comment]
Yes, I agree. I've been in contact for a few times but no support was given, unfortunatly. I hope they realise this is just some updating and fixing their permissions. On the other hand packages of 10G data would be installable aswell. Maybe it's just some sort of security issue they refuse to mention, I don't know. 👍

**Comment by ByJuri** [comment]
Hello i had a problem i dont understand what you mean nightwalker he says npm

**Comment by urbighomie** [comment]
> So I have managed to find a workaround which I'd like to share for other zap-users with issues.
> 
> Locally download and set up the discordroles file and configs. Then inside your folder run node js to afterwards 'npm install' the package.json. (how to: [here](https://www.youtube.com/watch?v=q19PLYrv9r4&ab_channel=Codevolution)). Then after you've done that delete package.json and package-lock file and move the files over to your server resources folder and start/ensure it inside the server.cfg.
> 
> That made this work for me.

how do you do this exactly

**Comment by RyanM2777** [comment]
How to do this:

Open CMD or Visual Studio Code Terminal - MAKE SURE YOUR IN THE FOLDER
then simply type npm i
then once its done delete package.json and package-lock files
then drag the folder into your FTP
